---
title: NSW Public Health Under Pressure as Demand reaches Record Levels
format: closeread-html
---

The Bureau of Health Information reports demand on the NSW health system. 

:::: cr-section
Health Minister Ryan Park blames Bed Block for the pressure.

In the last 3 months @cr-features

408,518 ambulance calls @cr-plotCalls
300,367 ambulance incidents @cr-plotIncidents
820,009 emergency department attendances @cr-plotResponses


::: {#cr-features}
1.  Highlighting
2.  Zooming
3.  Panning
:::

::: {#cr-plot}
```{r}
#| warning: false
#| message: false

#load package
library(tidyverse)

ambulance <- tribble(
  ~Year, ~Calls, ~Responses, ~Incidents, ~Patient_transports,
  2020, 333, 320, 250, 192,
  2021, 345, 321, 252, 187,
  2022, 360, 348, 270, 195,
  2023, 360, 378, 285, 204,
  2024, 380, 390, 292, 208,
  2025, 409, 392, 300, 214
)

ambulance_long <- pivot_longer(
  ambulance,
  -Year,
  names_to = "Measure",
  values_to = "Value"
)

highlight_plot <- function(highlight){

ggplot(ambulance_long,
       aes(Year, Value,
           group = Measure,
           colour = Measure == highlight)) +

  geom_line(linewidth = 1.3) +

  scale_colour_manual(values = c("grey80", "#0072B2"), guide = "none") +

  labs(
    title = highlight,
    x = NULL,
    y = "Thousands"
  ) +

  theme_minimal(base_size = 14)
}
```
:::

:::{#cr-plotCalls}

```{r}
highlight_plot("Calls")
```


:::

:::{#cr-plotResponses}

```{r}
highlight_plot("Responses")
```
:::

:::{#cr-plotIncidents}

```{r}
highlight_plot("Incidents")

```
:::

::::
